[package]
name = "tls_expires"
version = "0.1.0"
authors = ["Shisei Hanai <ruimo.uno@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.10"
chrono-tz = "0.5.1"
clap = "2.31.2"
